# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/AUC/Risc v/Risc v.cache/wt} [current_project]
set_property parent.project_path {C:/Users/AUC/Risc v/Risc v.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/AUC/Risc v/Risc v.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Projects/New folder/ALU.v}
  {D:/Projects/New folder/ALUControlUnit.v}
  {D:/Projects/New folder/ControlUnit.v}
  {D:/Projects/New folder/DFlipFlop.v}
  {D:/Projects/New folder/DataMem.v}
  {D:/Projects/New folder/ForwardingUnit.v}
  {D:/Projects/New folder/FullAdder.v}
  {D:/Projects/New folder/ImmGen.v}
  {D:/Projects/New folder/InstMem.v}
  {D:/Projects/New folder/MUX2x1.v}
  {D:/Projects/New folder/MUX4x1.v}
  {D:/Projects/New folder/NBitMUX2x1.v}
  {D:/Projects/New folder/NBitRegister.v}
  {D:/Projects/New folder/RCA.v}
  {D:/Projects/New folder/RegFile.v}
  {D:/Projects/New folder/ShiftLeft.v}
  {D:/Projects/New folder/RISCV_pipeline.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RISCV_pipeline -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_pipeline_utilization_synth.rpt -pb RISCV_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
