# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/AUC/Second Day/Second Day.cache/wt} [current_project]
set_property parent.project_path {C:/Users/AUC/Second Day/Second Day.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/AUC/Second Day/Second Day.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Projects/Final Project 2/defines.v}
  {D:/Projects/Final Project 2/ALU.v}
  {D:/Projects/Final Project 2/ALUControlUnit.v}
  {D:/Projects/Final Project 2/ControlUnit.v}
  {D:/Projects/Final Project 2/DFlipFlop.v}
  {D:/Projects/Final Project 2/DataMem.v}
  {D:/Projects/Final Project 2/ForwardingUnit.v}
  {D:/Projects/Final Project 2/FullAdder.v}
  {D:/Projects/Final Project 2/ImmGen.v}
  {D:/Projects/Final Project 2/InstMem.v}
  {D:/Projects/Final Project 2/MUX2x1.v}
  {D:/Projects/Final Project 2/MUX4x1.v}
  {D:/Projects/Final Project 2/NBitMUX2x1.v}
  {D:/Projects/Final Project 2/NBitRegister.v}
  {D:/Projects/Final Project 2/RCA.v}
  {D:/Projects/Final Project 2/RegFile.v}
  {D:/Projects/Final Project 2/Shift.v}
  {D:/Projects/Final Project 2/RISCV_pipeline.v}
  {D:/Projects/Final Project 2/HazardDetectionUnit.v}
  {D:/Projects/Final Project 2/Conditional_Branches.v}
  {D:/Projects/Final Project 2/BCD.v}
  {D:/Projects/Final Project 2/Datapath.v}
  {D:/Projects/Final Project 2/Four_Digit_Seven_Segment_Driver_Optimized.v}
  {D:/Projects/Final Project 2/LoadUnit.v}
  {D:/Projects/Final Project 2/ShiftLeft.v}
  {D:/Projects/Final Project 2/StoreUnit.v}
  {D:/Projects/Final Project 2/topModule.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RISCV_pipeline -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_pipeline_utilization_synth.rpt -pb RISCV_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
